# Generated by Django 3.1.3 on 2021-02-28 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssai_app', '0005_auto_20210220_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 28, 6, 36, 28, 43393, tzinfo=utc)),
        ),
    ]
