# Generated by Django 3.1.3 on 2021-02-28 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssai_app', '0006_auto_20210228_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='pay',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 28, 6, 38, 25, 739124, tzinfo=utc)),
        ),
    ]
